### ISSUE TITLE
Consider splitting the protocol implementations into another crate

### ISSUE THREAD

**Issue by notgull** [hapsoc/hring#39]
Right now, this crate contains an implementation of HTTP 1.1. However, one of my issues with `hyper` is that all of the protocol code is welded to the I/O code, and it's generally very hard to separate them if you want to do something with just the protocol code. For example, if I wanted to write my own HTTP implementation but using a synchronous API instead of the ring-based API, it would be preferable to use an HTTP protocol implementation that's already in use by well-established pieces of software in the ecosystem rather than duplicating time and effort by reimplementing my own.

See [this page](https://sans-io.readthedocs.io/index.html) for more information on this idea. A success story currently in use in the Rust ecosystem is [`x11rb-protocol`](https://github.com/psychon/x11rb/tree/master/x11rb-protocol), which is currently in use by `x11rb` as well as my own implementation of X11, `breadx`.

I'd like to make sure this crate goes in that direction. It would involve taking the code currently in the `h1` module and splitting the parts that deal with the protocol out into another crate. If this is desired, I can implement this.

**Comment by fasterthanlime** [comment]
I'm aware of the sans-io philosophy and I appreciate it, but it's outside the scope of this project _for now_. It essentially turns all the logic into a state machine, and for now I'd just like to get h1+h2 working as fast as possible on top of io-uring, and I might reconsider separating the protocol/IO bits later. 

For context, I took a sans-io approach in https://github.com/fasterthanlime/rc-zip and it is a LOT of boilerplate. State machines are really verbose in Rust.

I'm not saying it will forever be this way, but I just don't want to focus on this for now (nor do I want to focus on reviewing PRs going in this direction for now).

**Comment by fasterthanlime** [comment]
Just gonna go ahead and close this issue as long as I'm not planning on doing that - closed, but not forgotten.

I think potentially the h1/h2 parser parts might be extracted in other crates, but in the short term that's a higher maintenance burden. They're neatly in their own respective modules for now, they could be made generic over the input type and extracted later.

The h2 server logic might be made IO-independent later, right now it works as an event loop, but none of the flow control / prioritizing is done yet, so I don't understand the problem well enough to do sans-IO for now.
